eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://dev-cetcfg.combined.energy.aws:8762/eureka/

spring:
  zipkin:
    base-url: http://dev-cetcfg.combined.energy.aws:9412/
