eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.21.64.207:8761/eureka/
    
spring:
  zipkin:
    base-url: http://10.21.64.207:9411/

active-mq:
  broker-url: tcp://10.21.64.207:61616
