eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    
zipkin:
  baseUrl: http://localhost:9411/

active-mq:
  broker-url: tcp://localhost:61616
